image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - dist/craftmyself/browser
    expire_in: 1 hour


deploy:
  stage: deploy
  needs: ["build"]
  script:
    - npm install -g firebase-tools
    - firebase deploy --only hosting --project prod --token "$FIREBASE_TOKEN"
  only:
    - main  
